# Generated by Django 4.1.3 on 2022-12-07 09:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0003_fish_fish_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='description',
            field=models.TextField(blank=True, max_length=1300, null=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
