# Generated by Django 4.1.3 on 2022-12-08 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0004_alter_fish_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fish',
            options={'ordering': ('name',), 'verbose_name_plural': 'Fish'},
        ),
    ]
