# Generated by Django 4.1.3 on 2022-12-07 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fishbook.photos.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fish', '0004_alter_fish_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/', validators=[fishbook.photos.validators.validate_image])),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=30, null=True)),
                ('publication_date', models.DateField(auto_now=True)),
                ('fishing_style', models.CharField(blank=True, choices=[('float_fishing', 'Float fishing'), ('feeder_fishing', 'Feeder fishing'), ('fly_fishing', 'Fly fishing'), ('carp_fishing', 'Carp fishing'), ('spin_fishing', 'Spin fishing'), ('ice_fishing', 'Ice fishing'), ('trolling_fishing', 'Trolling fishing'), ('salt_water_fishing', 'Salt water fishing'), ('spear_fishing', 'Spear fishing')], max_length=18, null=True)),
                ('tagged_fish', models.ManyToManyField(blank=True, to='fish.fish')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
