# Generated by Django 4.1.3 on 2023-07-01 10:50

import cloudinary.models
from django.db import migrations
import fishbook.photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[fishbook.photos.validators.validate_image]),
        ),
    ]
