# Generated by Django 4.1.3 on 2022-12-14 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fishbook.photos.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fish', '0005_alter_fish_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicLake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Lake Name')),
                ('photo', models.ImageField(null=True, upload_to='lake_pictures/', validators=[fishbook.photos.validators.validate_image], verbose_name='Lake Photo')),
                ('region', models.CharField(max_length=30, verbose_name='Region')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('google_maps_link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Google Link')),
                ('fish', models.ManyToManyField(to='fish.fish', verbose_name='Fish')),
            ],
        ),
        migrations.CreateModel(
            name='PrivateLake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Lake Name')),
                ('photo', models.ImageField(null=True, upload_to='lake_pictures/', validators=[fishbook.photos.validators.validate_image], verbose_name='Lake Photo')),
                ('region', models.CharField(max_length=30, verbose_name='Region')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Address')),
                ('google_maps_link', models.CharField(blank=True, max_length=300, null=True, verbose_name='Google Link')),
                ('phone', models.CharField(blank=True, max_length=25, null=True, verbose_name='Phone')),
                ('day_tax', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fish', models.ManyToManyField(to='fish.fish', verbose_name='Fish')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Lake Owner')),
            ],
        ),
    ]
