# Generated by Django 4.1.3 on 2023-07-01 10:50

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0002_alter_publiclake_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publiclake',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Lake Photo'),
        ),
    ]
