# Generated by Django 4.1.3 on 2023-07-01 10:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lakes', '0003_alter_publiclake_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatelake',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='Lake Photo'),
        ),
    ]
