# Generated by Django 4.1.3 on 2022-12-07 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fishing_style',
            field=models.CharField(blank=True, choices=[('float_fishing', 'Float fishing'), ('feeder_fishing', 'Feeder fishing'), ('fly_fishing', 'Fly fishing'), ('carp_fishing', 'Carp fishing'), ('spin_fishing', 'Spin fishing'), ('ice_fishing', 'Ice fishing'), ('trolling_fishing', 'Trolling fishing'), ('salt_water_fishing', 'Salt water fishing'), ('spear_fishing', 'Spear fishing')], max_length=18, null=True),
        ),
    ]
