# Generated by Django 4.1.3 on 2023-07-01 10:06

import cloudinary.models
from django.db import migrations
import fishbook.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_fishing_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[fishbook.accounts.validators.validate_image]),
        ),
    ]
